### ISSUE TITLE
False positive on `top-scorers`

### ISSUE THREAD

**Issue by FabHof** [exercism/elm-analyzer#51] opened 2022-11-11 16:28 UTC
``` elm
removeInsignificantPlayers : Int -> Dict PlayerName Int -> Dict PlayerName Int
removeInsignificantPlayers goalThreshold playerGoalCounts =
    playerGoalCounts
        |> Dict.filter (\_ count -> count >= goalThreshold)
```
This solution triggers `removeInsignificantPlayersMustUseFilter` although Dict.filter is used

**Comment by ceddlyburge** [comment] 2022-11-11 16:39
Thanks Fabian, we will look in to this.

**Comment by jiegillet** [comment] 2022-11-12 01:20
Hi @FabHof,
I can't seem to reproduce this.

Would you mind sharing your full solution and copy the comment you saw?
Alternatively, you could send us a mentoring link so we can take a look ourselves.
<img width="1079" alt="Screen Shot 2022-11-12 at 10 19 49" src="https://user-images.githubusercontent.com/16929078/201449787-494b74c7-20e8-4849-a3de-1fb7ab9a1343.png">

**Comment by FabHof** [comment] 2022-11-12 13:57
Sure, here it is: https://exercism.org/mentoring/external_requests/41d0f02be3a34ea2a9f6853d8133a32e

**Comment by jiegillet** [comment] 2022-11-12 14:53
Thank you for sharing, I've identified the problem.

You received [this comment](https://github.com/exercism/website-copy/blob/main/analyzer-comments/elm/top-scorers/use_insert.md), which is supposed to tell you about another problem, but instead it is a duplicate of [this one](https://github.com/exercism/website-copy/blob/main/analyzer-comments/elm/top-scorers/use_filter.md). @ceddlyburge, could I ask you to rewrite the comment?

The real comment should be about this function:
```elm
resetPlayerGoalCount : PlayerName -> Dict PlayerName Int -> Dict PlayerName Int
resetPlayerGoalCount playerName playerGoalCounts =
    playerGoalCounts
        |> Dict.update playerName (\\_ -> Just 0)
```
and tell you that `Dict.insert` is the most appropriate function to use in this case because it doesn't require to define a function unlike `Dict.update`.

**Comment by ceddlyburge** [comment] 2022-11-12 15:40
Thanks @jie, I'll take a look at that ...

**Closed** 2022-11-12 23:24 UTC
